openapi: 3.0.0
info:
  title: "Demo api"
  description: "An API for demo"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /:
    post:
      operationId: "app.index"
      tags:
        - "app"
      summary: "Get the app"
      responses:
        "200":
          description: "Successful"
  /exit:
    post:
      operationId: "app.exit"
      tags:
        - "app"
      summary: "Exit the app"
      responses:
        "200":
          description: "Successfully exit"
  /ui:
    get:
      operationId: "app.ui"
      tags:
        - "app"
      summary: "Get swagger ui"
      responses:
        "200":
          description: "Success"
  /openapi.json:
    get:
      operationId: "app.openapi"
      tags:
        - "app"
      summary: "Get swagger json"
      responses:
        "200":
          description: "Success"
  /measurements:
    get:
      operationId: "measurements.read_all"
      tags:
        - "Measurements"
      summary: "Read the list of all measurements"
      responses:
        "200":
          description: "Successfully read measurements list"